version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10  # Python 3.10 with common tools preinstalled
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: echo "No tests yet, skipping..."

      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Build Docker image
          command: docker build -t web-app .

      - run:
          name: Log in to DockerHub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "sachin62" --password-stdin

      - run:
          name: Push image to DockerHub
          command: |
            IMAGE="sachin62/web-app"
            docker tag web-app $IMAGE:latest
            docker push sachin62/web-app:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build

